### ISSUE TITLE
http-errors come out nasty

### ISSUE THREAD

**Issue by Beanow** [Avaq/serialize-http-error#1]
Using [http-errors](https://www.npmjs.com/package/http-errors) like https://github.com/Avaq/node-server-skeleton/blob/master/src/routes/error.js#L11

Produces this body:

```json
{
  "message":"There's nothing at GET /hello",
  "status":404,
  "statusCode":404,
  "expose":true,
  "name":"NotFoundError"
}
```

Status and expose in particular are redundant I believe.

**Comment by Avaq** [comment]
Works as intended.

When an object is to be exposed, all of its properties are exposed. We make no attempts to show things as prettier than they are. Any such attempt would surely make debugging harder.
